[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
optimizer = true
optimizer_runs = 33333

[dependencies]
"@openzeppelin-contracts" = "5.2.0"
"@openzeppelin-contracts-upgradeable" = "5.2.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
single_line_statement_blocks = "single"
sort_imports = true