[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[dependencies]
"@openzeppelin-contracts" = "5.1.0"
"@openzeppelin-contracts-upgradeable" = "5.1.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
